spring.application.name=report-engine


spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/report
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
# 禁用 OpenSessionInView，避免视图渲染阶段持有 DB 连接拖慢业务
spring.jpa.open-in-view=false
